export const types={
    GET_BOOKS: 'SUCCESS_GET_BOOKS_CALL',
    GET_DESCRIPTION: 'SUCCESS_DESCRIPTION_DATA_CALL',
    SORT_BY_TITLE: 'SORT_BY_TITLE',
    SORT_BY_YEAR: 'SORT_BY_YEAR',
    SORT_BY_EDITION: 'SORT_BY_EDITION'
}